### ISSUE TITLE
This plugin was made by

### ISSUE THREAD

**Issue by ghost** [MCrafterss/UserGeo#1]
@applqpak

**Comment by ghost** [comment]
and u guys edited it

**Comment by xZeroMCPE** [comment]
ffs, haven't you notive that the original author added it.

https://github.com/MCrafterss/UserGeo/commit/ac9c014b3036200c31402aed95a0dcab84546f5d

**Comment by MiroTheSuperDev** [comment]
Applqpak developed it for mcrafters and posted it here .

MCrafters never and will never have any copyright issues .

**Comment by MiroTheSuperDev** [comment]
Applqpak developed it for mcrafters and posted it here .

MCrafters never and will never have any copyright issues .

**Comment by ghost** [comment]
@AmiroEmad oh okay
